language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.5-dev"
  - "3.6-dev"
  - "3.7-dev"
  - "pypy2.7"
  - "pypy3.5"
addons:
  apt:
    packages:
      - portaudio19-dev
install:
  - python setup.py install
script:
  - make test